### ISSUE TITLE
Don't include logback.xml in jar

### ISSUE THREAD

**Issue by nistvan86** [idio/bliki#3]
Adding bliki-core as a dependency to a Spring Boot application completely eliminates logging, overriding the default configuration.

Logging can be re-enabled by adding a logback.xml in the application's own jar, however this makes Logback throwing lot of warning messages on startup telling me there's multiple logback.xml files on the classpath.

Please remove logback.xml, it's a bad practice to put it into a non application jar.

**Comment by keynmol** [comment]
Hi @nistvan86. 

As this is an open source project under no active development (a fork, actually, but it seems the original project disappeared), you can submit a PR with proposed changes and we'll be happy to merge it.
