### ISSUE TITLE
What are the exact differences to the original Bliki code?

### ISSUE THREAD

**Issue by johann-petrak** [idio/bliki#4]
This is a fork of https://bitbucket.org/axelclk/info.bliki.wiki/wiki/Home but is there any documentation which, if any, differences exist between the two?

**Comment by keynmol** [comment]
Hi. To view the differences, you can check the commit history. There isn't many, just namespace handling: https://github.com/idio/bliki/commit/268dfb149b3a9002c334aeae4195c3a4aa430619

Main reason for creating this fork was to simplify our internal dependency resolution by utilising https://jitpack.io/

For the future - please create issues only to report bugs or propose new changes. We'll try to answer all other questions in https://gitter.im/idio-opensource/Lobby
